"""
mixtures.py

Defines a registry of dataset mixtures and weights for the Open-X Embodiment Datasets. Each dataset is associated with
a float "sampling weight"
"""

from typing import Dict, List, Tuple

# Dataset mixture name mapped to a list of tuples containing:
## {nakename: [(data_name, sampling_weight, robot_type)] }
DATASET_NAMED_MIXTURES = {
    "suqian_test": [("lerobot_subtask_full_modified_split_test_modified", 1.0, "agibot_genie1"),],
    "suqian_train": [("task_170_modified", 1.0, "agibot_genie1"),],
    "robocasa_300_ee": [("robocasa_24tasks_datasets/pick_and_place_lerobot_task24_sampled_300_epose_merged", 1.0, "fourier_gr1_arms_waist"),
                       ],
    "custom_dataset": [("custom_dataset_name", 1.0, "custom_robot_config"),],
    "custom_dataset_2": [
        ("custom_dataset_name_1", 1.0, "custom_robot_config"),
        ("custom_dataset_name_2", 1.0, "custom_robot_config"),
    ],
    "ego_dex": [("", 1.0, "ego_dex"),],
    "ego_dex_suqian_agi": [
        ("users/anonymous/ego30w_f_2kw", 1.0, "ego_dex"),
        ("datasets/suqian_agibot_lerobot_data/task_170_modified", 1.0, "agibot_genie1"),
    ],
    "sq_agi-beta_egodex-f": [
        ("../../workspace1/datasets/Agibot-Beta-Transformation/New_Full_merged-new/Agibot-Beta-Transformation-New_Full-split_part1", 1.0,
         "agibot_beta"),
        ("../../workspace1/datasets/Agibot-Beta-Transformation/New_Full_merged-new/Agibot-Beta-Transformation-New_Full-split_part2", 1.0,
         "agibot_beta"),
        ("../../workspace1/datasets/Agibot-Beta-Transformation/New_Full_merged-new/Agibot-Beta-Transformation-New_Full-split_part3", 1.0,
         "agibot_beta"),
        ("../../workspace1/datasets/Agibot-Beta-Transformation/New_Full_merged-new/Agibot-Beta-Transformation-New_Full-split_part4", 1.0,
         "agibot_beta"),
        ("../../workspace1/datasets/Agibot-Beta-Transformation/New_Full_merged-new/Agibot-Beta-Transformation-New_Full-split_part5", 1.0,
         "agibot_beta"),
     # ("../../workspace1/datasets/G1_task_all_merged-new/datasets-G1_task_all", 1.0, "agibot_genie1"),
        ("egodex30w_datasets/egodex_merge30w_fourier", 1.0, "egodex"),
     # ('../../workspace1/datasets/PhysicalAI-Robotics-GR00T-Teleop-Sim/LeRobot_eepose_merged', 1.0, 'fourier_gr1_arms_waist'),
     # ("robotwin_dataset/dataset_lerobot/aloha-agilex_550_single_task_eepose_merged", 1.0, "robotwin"),
    ],
    "sq_robocasa": [
        ("datasets/G1_task_all_merged-new_0508/datasets-G1_task_all_0508", 1.0, "agibot_genie1"),
        # ("datasets/Agibot-Beta-Transformation/New_Full_merged-new/Agibot-Beta-Transformation-New_Full-split_part1", 1.0, "agibot_beta"),
        # ("datasets/Agibot-Beta-Transformation/New_Full_merged-new/Agibot-Beta-Transformation-New_Full-split_part2", 1.0, "agibot_beta"),
        # ("datasets/Agibot-Beta-Transformation/New_Full_merged-new/Agibot-Beta-Transformation-New_Full-split_part3", 1.0, "agibot_beta"),
        # ("datasets/Agibot-Beta-Transformation/New_Full_merged-new/Agibot-Beta-Transformation-New_Full-split_part4", 1.0, "agibot_beta"),
        # ("datasets/Agibot-Beta-Transformation/New_Full_merged-new/Agibot-Beta-Transformation-New_Full-split_part5", 1.0, "agibot_beta"),
        # ("../../workspace1/datasets/Agibot-Beta-Transformation/New_Full_merged-new/Agibot-Beta-Transformation-New_Full-split_part5", 1.0,
        #  "agibot_beta"),
     # ("../../workspace1/datasets/G1_task_all_merged-new/datasets-G1_task_all", 1.0, "agibot_genie1"),
        # ("egodex30w_datasets/egodex_merge30w_fourier", 1.0, "egodex"),
        ('datasets/PhysicalAI-Robotics-GR00T-Teleop-Sim/LeRobot_eepose_merged', 1.0, 'fourier_gr1_arms_waist'),
        # ("robotwin_dataset/dataset_lerobot/aloha-agilex_550_single_task_eepose_merged", 1.0, "robotwin"),
    ],
    "sq_agi-beta_robocasa": [
        ("datasets/G1_task_all_merged-new_0508/datasets-G1_task_all_0508", 1.0, "agibot_genie1"),
        ("datasets/Agibot-Beta-Transformation/New_Full_merged-new/Agibot-Beta-Transformation-New_Full-split_part1", 1.0, "agibot_beta"),
        ("datasets/Agibot-Beta-Transformation/New_Full_merged-new/Agibot-Beta-Transformation-New_Full-split_part2", 1.0, "agibot_beta"),
        ("datasets/Agibot-Beta-Transformation/New_Full_merged-new/Agibot-Beta-Transformation-New_Full-split_part3", 1.0, "agibot_beta"),
        ("datasets/Agibot-Beta-Transformation/New_Full_merged-new/Agibot-Beta-Transformation-New_Full-split_part4", 1.0, "agibot_beta"),
        ("datasets/Agibot-Beta-Transformation/New_Full_merged-new/Agibot-Beta-Transformation-New_Full-split_part5", 1.0, "agibot_beta"),
        # ("../../workspace1/datasets/Agibot-Beta-Transformation/New_Full_merged-new/Agibot-Beta-Transformation-New_Full-split_part5", 1.0,
        #  "agibot_beta"),
     # ("../../workspace1/datasets/G1_task_all_merged-new/datasets-G1_task_all", 1.0, "agibot_genie1"),
        # ("egodex30w_datasets/egodex_merge30w_fourier", 1.0, "egodex"),
        ('datasets/PhysicalAI-Robotics-GR00T-Teleop-Sim/LeRobot_eepose_merged', 1.0, 'fourier_gr1_arms_waist'),
        # ("robotwin_dataset/dataset_lerobot/aloha-agilex_550_single_task_eepose_merged", 1.0, "robotwin"),
    ],
    "robocasa_merge": [
        ('../../workspace1/datasets/PhysicalAI-Robotics-GR00T-Teleop-Sim/LeRobot_eepose_merged', 1.0, 'fourier_gr1_arms_waist'),
    ],
    "sq_egodex-f_robotwin_robocasa": [
        ("egodex30w_datasets/egodex_merge30w_fourier", 1.0, "egodex"),
        ("suqian_agibot_lerobot_data/task_170_modified_train", 1.0, "agibot_genie1"),
     # ("AgiBotWorld-Beta-LeRobot", 1.0, "agibot_beta"),
        ('../../workspace1/datasets/PhysicalAI-Robotics-GR00T-Teleop-Sim/LeRobot_eepose_merged', 1.0, 'fourier_gr1_arms_waist'),
        ("robotwin_dataset/dataset_lerobot/aloha-agilex_550_single_task_eepose_merged", 1.0, "robotwin"),
    ],
     "sq_agi-beta_egodex-f_robotwin_robocasa": [
         ("egodex30w_datasets/egodex_merge30w_fourier", 1.0, "egodex"),
         ("suqian_agibot_lerobot_data/task_170_modified_train", 1.0, "agibot_genie1"),
         ("AgiBotWorld-Beta-LeRobot", 1.0, "agibot_beta"),
         ('../../workspace1/datasets/PhysicalAI-Robotics-GR00T-Teleop-Sim/LeRobot_eepose_merged', 1.0, 'fourier_gr1_arms_waist'),
         ("robotwin_dataset/dataset_lerobot/aloha-agilex_550_single_task_eepose_merged", 1.0, "robotwin"),
     ],
    "sq_agi-beta_egodex-f_nvwa-f_robotwin_robocasa": [
        ("datasets/G1_task_all_merged-new_0508/datasets-G1_task_all_0508", 1.0, "agibot_genie1"),
        ("datasets/Agibot-Beta-Transformation/New_Full_merged-new/Agibot-Beta-Transformation-New_Full-split_part1", 1.0, "agibot_beta"),
        ("datasets/Agibot-Beta-Transformation/New_Full_merged-new/Agibot-Beta-Transformation-New_Full-split_part2", 1.0, "agibot_beta"),
        ("datasets/Agibot-Beta-Transformation/New_Full_merged-new/Agibot-Beta-Transformation-New_Full-split_part3", 1.0, "agibot_beta"),
        ("datasets/Agibot-Beta-Transformation/New_Full_merged-new/Agibot-Beta-Transformation-New_Full-split_part4", 1.0, "agibot_beta"),
        ("datasets/Agibot-Beta-Transformation/New_Full_merged-new/Agibot-Beta-Transformation-New_Full-split_part5", 1.0, "agibot_beta"),
        ("../path/to/workspace/datasets/egodex30w_datasets/egodex_merge30w_fourier", 1.0, "egodex"),
        ('datasets/PhysicalAI-Robotics-GR00T-Teleop-Sim/LeRobot_eepose_merged', 1.0, 'fourier_gr1_arms_waist'),
        ("../path/to/workspace/datasets/robotwin_dataset/dataset_lerobot/aloha-agilex_550_single_task_eepose_merged", 1.0, "robotwin"),
        ("../path/to/workspace/nvwa2lerobot2/retarget_fourier_20260318_890h_re/lerobot_data", 0.1, "nvwa_f"),
        ("../path/to/workspace/nvwa2lerobot2/retarget_fourier_1000h_re/lerobot_data", 0.1, "nvwa_f"),
        # ("datasets/nvwa/lerobot_data", 0.1, "nvwa_f"),
    ],
    "robotwin_ee": [
        ("robotwin_dataset/dataset_lerobot/aloha-agilex_550_single_task_eepose_merged", 1.0, "robotwin"),
    ],
    "robotwin_robocasa": [
        ('../../workspace1/datasets/PhysicalAI-Robotics-GR00T-Teleop-Sim/LeRobot_eepose_merged', 1.0, 'fourier_gr1_arms_waist'),
        ("robotwin_dataset/dataset_lerobot/aloha-agilex_550_single_task_eepose_merged", 1.0, "robotwin"),
    ],
    "libero_all": [
        ("libero_object_no_noops_1.0.0_lerobot", 1.0, "libero_franka"),
        ("libero_goal_no_noops_1.0.0_lerobot", 1.0, "libero_franka"),
        ("libero_spatial_no_noops_1.0.0_lerobot", 1.0, "libero_franka"),
        ("libero_10_no_noops_1.0.0_lerobot", 1.0, "libero_franka"),
     # ("libero_90_no_noops_lerobot", 1.0, "libero_franka"),
    ],
    "bridge": [("bridge_orig_1.0.0_lerobot", 1.0, "oxe_bridge"),],
    "bridge_rt_1": [
        ("bridge_orig_1.0.0_lerobot", 1.0, "oxe_bridge"),
        ("fractal20220817_data_0.1.0_lerobot", 1.0, "oxe_rt1"),
    ],
    "demo_sim_pick_place": [("sim_pick_place", 1.0, "demo_sim_franka_delta_joints"),],
    "custom_dataset": [("custom_dataset_name", 1.0, "custom_robot_config"),],
    "custom_dataset_2": [
        ("custom_dataset_name_1", 1.0, "custom_robot_config"),
        ("custom_dataset_name_2", 1.0, "custom_robot_config"),
    ],
    "fourier_gr1_unified_1000": [
        ("gr1_unified.PnPBottleToCabinetClose_GR1ArmsAndWaistFourierHands_1000", 1.0, "fourier_gr1_arms_waist"),
        ("gr1_unified.PnPCanToDrawerClose_GR1ArmsAndWaistFourierHands_1000", 1.0, "fourier_gr1_arms_waist"),
        ("gr1_unified.PnPCupToDrawerClose_GR1ArmsAndWaistFourierHands_1000", 1.0, "fourier_gr1_arms_waist"),
        ("gr1_unified.PnPMilkToMicrowaveClose_GR1ArmsAndWaistFourierHands_1000", 1.0, "fourier_gr1_arms_waist"),
        ("gr1_unified.PnPPotatoToMicrowaveClose_GR1ArmsAndWaistFourierHands_1000", 1.0, "fourier_gr1_arms_waist"),
        ("gr1_unified.PnPWineToCabinetClose_GR1ArmsAndWaistFourierHands_1000", 1.0, "fourier_gr1_arms_waist"),
        ("gr1_unified.PosttrainPnPNovelFromCuttingboardToBasketSplitA_GR1ArmsAndWaistFourierHands_1000", 1.0, "fourier_gr1_arms_waist"),
        ("gr1_unified.PosttrainPnPNovelFromCuttingboardToCardboardboxSplitA_GR1ArmsAndWaistFourierHands_1000", 1.0,
         "fourier_gr1_arms_waist"),
        ("gr1_unified.PosttrainPnPNovelFromCuttingboardToPanSplitA_GR1ArmsAndWaistFourierHands_1000", 1.0, "fourier_gr1_arms_waist"),
        ("gr1_unified.PosttrainPnPNovelFromCuttingboardToPotSplitA_GR1ArmsAndWaistFourierHands_1000", 1.0, "fourier_gr1_arms_waist"),
        ("gr1_unified.PosttrainPnPNovelFromCuttingboardToTieredbasketSplitA_GR1ArmsAndWaistFourierHands_1000", 1.0,
         "fourier_gr1_arms_waist"),
        ("gr1_unified.PosttrainPnPNovelFromPlacematToBasketSplitA_GR1ArmsAndWaistFourierHands_1000", 1.0, "fourier_gr1_arms_waist"),
        ("gr1_unified.PosttrainPnPNovelFromPlacematToBowlSplitA_GR1ArmsAndWaistFourierHands_1000", 1.0, "fourier_gr1_arms_waist"),
        ("gr1_unified.PosttrainPnPNovelFromPlacematToPlateSplitA_GR1ArmsAndWaistFourierHands_1000", 1.0, "fourier_gr1_arms_waist"),
        ("gr1_unified.PosttrainPnPNovelFromPlacematToTieredshelfSplitA_GR1ArmsAndWaistFourierHands_1000", 1.0, "fourier_gr1_arms_waist"),
        ("gr1_unified.PosttrainPnPNovelFromPlateToBowlSplitA_GR1ArmsAndWaistFourierHands_1000", 1.0, "fourier_gr1_arms_waist"),
        ("gr1_unified.PosttrainPnPNovelFromPlateToCardboardboxSplitA_GR1ArmsAndWaistFourierHands_1000", 1.0, "fourier_gr1_arms_waist"),
        ("gr1_unified.PosttrainPnPNovelFromPlateToPanSplitA_GR1ArmsAndWaistFourierHands_1000", 1.0, "fourier_gr1_arms_waist"),
        ("gr1_unified.PosttrainPnPNovelFromPlateToPlateSplitA_GR1ArmsAndWaistFourierHands_1000", 1.0, "fourier_gr1_arms_waist"),
        ("gr1_unified.PosttrainPnPNovelFromTrayToCardboardboxSplitA_GR1ArmsAndWaistFourierHands_1000", 1.0, "fourier_gr1_arms_waist"),
        ("gr1_unified.PosttrainPnPNovelFromTrayToPlateSplitA_GR1ArmsAndWaistFourierHands_1000", 1.0, "fourier_gr1_arms_waist"),
        ("gr1_unified.PosttrainPnPNovelFromTrayToPotSplitA_GR1ArmsAndWaistFourierHands_1000", 1.0, "fourier_gr1_arms_waist"),
        ("gr1_unified.PosttrainPnPNovelFromTrayToTieredbasketSplitA_GR1ArmsAndWaistFourierHands_1000", 1.0, "fourier_gr1_arms_waist"),
        ("gr1_unified.PosttrainPnPNovelFromTrayToTieredshelfSplitA_GR1ArmsAndWaistFourierHands_1000", 1.0, "fourier_gr1_arms_waist"),
    ],
    "robocasa_teleop": [
        ('PhysicalAI-Robotics-GR00T-Teleop-Sim/LeRobot/gr1_unified.PnPBottleToCabinetClose', 1.0, 'fourier_gr1_arms_waist'),
        ('PhysicalAI-Robotics-GR00T-Teleop-Sim/LeRobot/gr1_unified.PnPCanToDrawerClose', 1.0, 'fourier_gr1_arms_waist'),
        ('PhysicalAI-Robotics-GR00T-Teleop-Sim/LeRobot/gr1_unified.PnPCupToDrawerClose', 1.0, 'fourier_gr1_arms_waist'),
        ('PhysicalAI-Robotics-GR00T-Teleop-Sim/LeRobot/gr1_unified.PnPMilkToMicrowaveClose', 1.0, 'fourier_gr1_arms_waist'),
        ('PhysicalAI-Robotics-GR00T-Teleop-Sim/LeRobot/gr1_unified.PnPPotatoToMicrowaveClose', 1.0, 'fourier_gr1_arms_waist'),
        ('PhysicalAI-Robotics-GR00T-Teleop-Sim/LeRobot/gr1_unified.PnPWineToCabinetClose', 1.0, 'fourier_gr1_arms_waist'),
        ('PhysicalAI-Robotics-GR00T-Teleop-Sim/LeRobot/gr1_unified.PosttrainPnPNovelFromCuttingboardToBasketSplitA', 1.0,
         'fourier_gr1_arms_waist'),
        ('PhysicalAI-Robotics-GR00T-Teleop-Sim/LeRobot/gr1_unified.PosttrainPnPNovelFromCuttingboardToCardboardboxSplitA', 1.0,
         'fourier_gr1_arms_waist'),
        ('PhysicalAI-Robotics-GR00T-Teleop-Sim/LeRobot/gr1_unified.PosttrainPnPNovelFromCuttingboardToPanSplitA', 1.0,
         'fourier_gr1_arms_waist'),
        ('PhysicalAI-Robotics-GR00T-Teleop-Sim/LeRobot/gr1_unified.PosttrainPnPNovelFromCuttingboardToPotSplitA', 1.0,
         'fourier_gr1_arms_waist'),
        ('PhysicalAI-Robotics-GR00T-Teleop-Sim/LeRobot/gr1_unified.PosttrainPnPNovelFromCuttingboardToTieredbasketSplitA', 1.0,
         'fourier_gr1_arms_waist'),
        ('PhysicalAI-Robotics-GR00T-Teleop-Sim/LeRobot/gr1_unified.PosttrainPnPNovelFromPlacematToBasketSplitA', 1.0,
         'fourier_gr1_arms_waist'),
        ('PhysicalAI-Robotics-GR00T-Teleop-Sim/LeRobot/gr1_unified.PosttrainPnPNovelFromPlacematToBowlSplitA', 1.0,
         'fourier_gr1_arms_waist'),
        ('PhysicalAI-Robotics-GR00T-Teleop-Sim/LeRobot/gr1_unified.PosttrainPnPNovelFromPlacematToPlateSplitA', 1.0,
         'fourier_gr1_arms_waist'),
        ('PhysicalAI-Robotics-GR00T-Teleop-Sim/LeRobot/gr1_unified.PosttrainPnPNovelFromPlacematToTieredshelfSplitA', 1.0,
         'fourier_gr1_arms_waist'),
        ('PhysicalAI-Robotics-GR00T-Teleop-Sim/LeRobot/gr1_unified.PosttrainPnPNovelFromPlateToBowlSplitA', 1.0, 'fourier_gr1_arms_waist'),
        ('PhysicalAI-Robotics-GR00T-Teleop-Sim/LeRobot/gr1_unified.PosttrainPnPNovelFromPlateToCardboardboxSplitA', 1.0,
         'fourier_gr1_arms_waist'),
        ('PhysicalAI-Robotics-GR00T-Teleop-Sim/LeRobot/gr1_unified.PosttrainPnPNovelFromPlateToPanSplitA', 1.0, 'fourier_gr1_arms_waist'),
        ('PhysicalAI-Robotics-GR00T-Teleop-Sim/LeRobot/gr1_unified.PosttrainPnPNovelFromPlateToPlateSplitA', 1.0, 'fourier_gr1_arms_waist'),
        ('PhysicalAI-Robotics-GR00T-Teleop-Sim/LeRobot/gr1_unified.PosttrainPnPNovelFromTrayToCardboardboxSplitA', 1.0,
         'fourier_gr1_arms_waist'),
        ('PhysicalAI-Robotics-GR00T-Teleop-Sim/LeRobot/gr1_unified.PosttrainPnPNovelFromTrayToPlateSplitA', 1.0, 'fourier_gr1_arms_waist'),
        ('PhysicalAI-Robotics-GR00T-Teleop-Sim/LeRobot/gr1_unified.PosttrainPnPNovelFromTrayToPotSplitA', 1.0, 'fourier_gr1_arms_waist'),
        ('PhysicalAI-Robotics-GR00T-Teleop-Sim/LeRobot/gr1_unified.PosttrainPnPNovelFromTrayToTieredbasketSplitA', 1.0,
         'fourier_gr1_arms_waist'),
        ('PhysicalAI-Robotics-GR00T-Teleop-Sim/LeRobot/gr1_unified.PosttrainPnPNovelFromTrayToTieredshelfSplitA', 1.0,
         'fourier_gr1_arms_waist')
    ],
    "robocasa_teleop_ee": [
        ('PhysicalAI-Robotics-GR00T-Teleop-Sim/LeRobot_eepose/gr1_unified.PnPBottleToCabinetClose_ee', 1.0, 'fourier_gr1_arms_waist'),
        ('PhysicalAI-Robotics-GR00T-Teleop-Sim/LeRobot_eepose/gr1_unified.PnPCanToDrawerClose_ee', 1.0, 'fourier_gr1_arms_waist'),
        ('PhysicalAI-Robotics-GR00T-Teleop-Sim/LeRobot_eepose/gr1_unified.PnPCupToDrawerClose_ee', 1.0, 'fourier_gr1_arms_waist'),
        ('PhysicalAI-Robotics-GR00T-Teleop-Sim/LeRobot_eepose/gr1_unified.PnPMilkToMicrowaveClose_ee', 1.0, 'fourier_gr1_arms_waist'),
        ('PhysicalAI-Robotics-GR00T-Teleop-Sim/LeRobot_eepose/gr1_unified.PnPPotatoToMicrowaveClose_ee', 1.0, 'fourier_gr1_arms_waist'),
        ('PhysicalAI-Robotics-GR00T-Teleop-Sim/LeRobot_eepose/gr1_unified.PnPWineToCabinetClose_ee', 1.0, 'fourier_gr1_arms_waist'),
        ('PhysicalAI-Robotics-GR00T-Teleop-Sim/LeRobot_eepose/gr1_unified.PosttrainPnPNovelFromCuttingboardToBasketSplitA_ee', 1.0,
         'fourier_gr1_arms_waist'),
        ('PhysicalAI-Robotics-GR00T-Teleop-Sim/LeRobot_eepose/gr1_unified.PosttrainPnPNovelFromCuttingboardToCardboardboxSplitA_ee', 1.0,
         'fourier_gr1_arms_waist'),
        ('PhysicalAI-Robotics-GR00T-Teleop-Sim/LeRobot_eepose/gr1_unified.PosttrainPnPNovelFromCuttingboardToPanSplitA_ee', 1.0,
         'fourier_gr1_arms_waist'),
        ('PhysicalAI-Robotics-GR00T-Teleop-Sim/LeRobot_eepose/gr1_unified.PosttrainPnPNovelFromCuttingboardToPotSplitA_ee', 1.0,
         'fourier_gr1_arms_waist'),
        ('PhysicalAI-Robotics-GR00T-Teleop-Sim/LeRobot_eepose/gr1_unified.PosttrainPnPNovelFromCuttingboardToTieredbasketSplitA_ee', 1.0,
         'fourier_gr1_arms_waist'),
        ('PhysicalAI-Robotics-GR00T-Teleop-Sim/LeRobot_eepose/gr1_unified.PosttrainPnPNovelFromPlacematToBasketSplitA_ee', 1.0,
         'fourier_gr1_arms_waist'),
        ('PhysicalAI-Robotics-GR00T-Teleop-Sim/LeRobot_eepose/gr1_unified.PosttrainPnPNovelFromPlacematToBowlSplitA_ee', 1.0,
         'fourier_gr1_arms_waist'),
        ('PhysicalAI-Robotics-GR00T-Teleop-Sim/LeRobot_eepose/gr1_unified.PosttrainPnPNovelFromPlacematToPlateSplitA_ee', 1.0,
         'fourier_gr1_arms_waist'),
        ('PhysicalAI-Robotics-GR00T-Teleop-Sim/LeRobot_eepose/gr1_unified.PosttrainPnPNovelFromPlacematToTieredshelfSplitA_ee', 1.0,
         'fourier_gr1_arms_waist'),
        ('PhysicalAI-Robotics-GR00T-Teleop-Sim/LeRobot_eepose/gr1_unified.PosttrainPnPNovelFromPlateToBowlSplitA_ee', 1.0,
         'fourier_gr1_arms_waist'),
        ('PhysicalAI-Robotics-GR00T-Teleop-Sim/LeRobot_eepose/gr1_unified.PosttrainPnPNovelFromPlateToCardboardboxSplitA_ee', 1.0,
         'fourier_gr1_arms_waist'),
        ('PhysicalAI-Robotics-GR00T-Teleop-Sim/LeRobot_eepose/gr1_unified.PosttrainPnPNovelFromPlateToPanSplitA_ee', 1.0,
         'fourier_gr1_arms_waist'),
        ('PhysicalAI-Robotics-GR00T-Teleop-Sim/LeRobot_eepose/gr1_unified.PosttrainPnPNovelFromPlateToPlateSplitA_ee', 1.0,
         'fourier_gr1_arms_waist'),
        ('PhysicalAI-Robotics-GR00T-Teleop-Sim/LeRobot_eepose/gr1_unified.PosttrainPnPNovelFromTrayToCardboardboxSplitA_ee', 1.0,
         'fourier_gr1_arms_waist'),
        ('PhysicalAI-Robotics-GR00T-Teleop-Sim/LeRobot_eepose/gr1_unified.PosttrainPnPNovelFromTrayToPlateSplitA_ee', 1.0,
         'fourier_gr1_arms_waist'),
        ('PhysicalAI-Robotics-GR00T-Teleop-Sim/LeRobot_eepose/gr1_unified.PosttrainPnPNovelFromTrayToPotSplitA_ee', 1.0,
         'fourier_gr1_arms_waist'),
        ('PhysicalAI-Robotics-GR00T-Teleop-Sim/LeRobot_eepose/gr1_unified.PosttrainPnPNovelFromTrayToTieredbasketSplitA_ee', 1.0,
         'fourier_gr1_arms_waist'),
        ('PhysicalAI-Robotics-GR00T-Teleop-Sim/LeRobot_eepose/gr1_unified.PosttrainPnPNovelFromTrayToTieredshelfSplitA_ee', 1.0,
         'fourier_gr1_arms_waist')
    ],
    "BEHAVIOR_challenge": [("BEHAVIOR_challenge", 1.0, "R1Pro"),],
    "SO101_pick": [("pick_dataset_name", 1.0, "SO101"),],
    "arx_x5": [("arx_x5", 1.0, "arx_x5"),],
    "robotwin": [
        ("adjust_bottle", 1.0, "robotwin"),
        ("beat_block_hammer", 1.0, "robotwin"),
        ("blocks_ranking_rgb", 1.0, "robotwin"),
        ("blocks_ranking_size", 1.0, "robotwin"),
        ("click_alarmclock", 1.0, "robotwin"),
        ("click_bell", 1.0, "robotwin"),
        ("dump_bin_bigbin", 1.0, "robotwin"),
        ("grab_roller", 1.0, "robotwin"),
        ("handover_block", 1.0, "robotwin"),
        ("handover_mic", 1.0, "robotwin"),
        ("hanging_mug", 1.0, "robotwin"),
        ("lift_pot", 1.0, "robotwin"),
        ("move_can_pot", 1.0, "robotwin"),
        ("move_pillbottle_pad", 1.0, "robotwin"),
        ("move_playingcard_away", 1.0, "robotwin"),
        ("move_stapler_pad", 1.0, "robotwin"),
        ("open_laptop", 1.0, "robotwin"),
        ("open_microwave", 1.0, "robotwin"),
        ("pick_diverse_bottles", 1.0, "robotwin"),
        ("pick_dual_bottles", 1.0, "robotwin"),
        ("place_a2b_left", 1.0, "robotwin"),
        ("place_a2b_right", 1.0, "robotwin"),
        ("place_bread_basket", 1.0, "robotwin"),
        ("place_bread_skillet", 1.0, "robotwin"),
        ("place_burger_fries", 1.0, "robotwin"),
        ("place_can_basket", 1.0, "robotwin"),
        ("place_cans_plasticbox", 1.0, "robotwin"),
        ("place_container_plate", 1.0, "robotwin"),
        ("place_dual_shoes", 1.0, "robotwin"),
        ("place_empty_cup", 1.0, "robotwin"),
        ("place_fan", 1.0, "robotwin"),
        ("place_mouse_pad", 1.0, "robotwin"),
        ("place_object_basket", 1.0, "robotwin"),
        ("place_object_scale", 1.0, "robotwin"),
        ("place_object_stand", 1.0, "robotwin"),
        ("place_phone_stand", 1.0, "robotwin"),
        ("place_shoe", 1.0, "robotwin"),
        ("press_stapler", 1.0, "robotwin"),
        ("put_bottles_dustbin", 1.0, "robotwin"),
        ("put_object_cabinet", 1.0, "robotwin"),
        ("rotate_qrcode", 1.0, "robotwin"),
        ("scan_object", 1.0, "robotwin"),
        ("shake_bottle", 1.0, "robotwin"),
        ("shake_bottle_horizontally", 1.0, "robotwin"),
        ("stack_blocks_three", 1.0, "robotwin"),
        ("stack_blocks_two", 1.0, "robotwin"),
        ("stack_bowls_three", 1.0, "robotwin"),
        ("stack_bowls_two", 1.0, "robotwin"),
        ("stamp_seal", 1.0, "robotwin"),
        ("turn_switch", 1.0, "robotwin"),
    ],
    "robotwin_task1": [("adjust_bottle", 1.0, "robotwin"),],
    "robotwin_task2": [
        ("place_a2b_left", 1.0, "robotwin"),
        ("place_a2b_right", 1.0, "robotwin"),
    ],
    "multi_robot": [("LEROBOT_LIBERO_DATA/libero_10_no_noops_1.0.0_lerobot", 1.0, "libero_franka"),
     # ("OXE_LEROBOT_DATASET/bridge_orig_1.0.0_lerobot", 1.0, "oxe_bridge"),
                   ],
}
